services:
  backend:
    volumes:
      - ./backend:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  ingestor:
    volumes:
      - ./ingestor:/app

  frontend-dev:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
      - ./volumes/frontend/node_modules:/app/node_modules
    ports:
      - "3000:5173"
    command: ["sh", "-lc", "npm install && npm run dev"]
    networks:
      - iot-network
